site:
  name: example

global:
  pattern: multicluster-devsecops
  repoURL: "https://github.com/<git-fork>/multicluster-devsecops"
  targetRevision: main

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  # Should be set consistently with quay enterprise setup
  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example

devel:
  appURL: AUTOMATED
  image: AUTOMATED
  namespace: AUTOMATED
  roxCTLImage: AUTOMATED

clusterGroup:
  name: testgroup
