apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: react-pipelinerun
  namespace: {{ .Values.devel.namespace }}
spec:
  params:
    - name: "github-repo-revision"
      value: "main"
    - name: "github-repo-url"
      value: {{ .Values.devel.appURL }}
    - name: "context-dir"
      value: "/"
    - name: "image-name"
      value: {{ .Values.devel.image }}
    - name: "is-name"
      value: "chat-client"
  pipelineRef:
    name: build-and-deploy
  podTemplate:
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc
  serviceAccountName: pipeline
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc